apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: drupal
  labels:
    app: drupal
spec:
  type: NodePort
  ports:
  - port: 5000
    name: drupal
    targetPort: 80
    nodePort: 30100
  selector:
    app: drupal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
  name: drupal
spec:      
  selector: 
    matchLabels:
      app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: localhost:32000/dg2020:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
